USE OPRISKLIB;

INSERT INTO `OPRISK_BOOK_STORE` (`OPRISK_BOOK_STORE_ID`, `TITLE`, `AUTHOR`, `PUBLISH_DATE`, `SUB_TITLE`, `ORIGIN_TITLE`, `IMAGE`, `TRANSLATOR`, `PAGES`, `PRICE`, `PUBLISHER`, `ISBN_10`, `ISBN_13`, `AUTHOR_INTRO`, `SUMMARY`, `BOOK_OWNER`, `IS_IN_LIBRARY`, `IS_ACTIVE`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`) VALUES (10,'R语言编程艺术','[\"（美）Norman Matloff\"]','2013-5',NULL,'The Art of R Programming: A Tour of Statistical Software Design','http://img4.douban.com/mpic/s26540607.jpg','[\"陈堰平\",\"邱怡轩\",\"潘岚锋 等\"]',303,'69.00','机械工业出版社','7111423143','9787111423140','Norman Matloff 著名计算机科学家兼统计学家，美国加州大学戴维斯分校计算机科学系教授，曾是该校统计专业的创建者之一，并担任过统计学教授。对并行编程、网络流量、数据挖掘、磁盘系统性能等方面的技术都有深入的研究。乐于分享，撰写了多部广受欢迎的关于软件开发的在线教程，多次为《纽约时报》、《华盛顿邮报》、《福布斯杂志》以及《洛杉矶时报》撰写文章，同时他还是《The Art of Debugging》的作者之一。','【编辑推荐】\n这本书涵盖了R语言编程的诸多方面，尤其在面向对象编程、程序调试、提升程序运行速度以及并行计算等方面，填补了同类图书的空白。关于程序调试的章节更是作者多年经验的总结。不管是初学者还是有一定编程经验的读者，阅读这本书都会有所收获。\n——统计之都\n【内容简介】\nR语言是世界上最流行的用于数据处理和统计分析的脚本语言。考古学家用它来跟踪古代文明的传播，医药公司用它来探索哪种药物更安全、更有效，精算师用它评估金融风险以保证市场的平稳运行。总之，在大数据时代，统计数据、分析数据都离不开计算机软件的支持，在这方面R语言尤其出色。\n本书将带领你踏上R语言软件开发之旅，从最基本的数据类型和数据结构开始，到闭包、递归和匿名函数等高级主题，由浅入深，讲解细腻，读者完全不需要统计学的知识，甚至不需要编程基础。而书中提到的很多高级编程技巧，都是作者多年编程经验的总结，对有经验的开发者也大有裨益。本书精选了44个扩展案例，这些案例都源自于作者亲身参与过的咨询项目，都是与数据分析相关的，生动展示了R语言在统计学中的高效应用。\n本书核心内容：\n R语言的完整语法以及R语言的编程技巧\n 创建精美图形来展示复杂数据和函数\n 使用并行计算和向量化的方法编写更高效的代码\n 使用R对C/C++和Python的接口来提高计算速度或增加功能\n 文本分析、图像处理等领域新的R包\n 使用高级调试技巧清除代码里恼人的错误\n 包含许多“扩展案例”，展示完整的、特定用途的函数，并针对同一个问题讨论了不同的设计方案，以便分析高效准确的做法。\n 在恰当的时候介绍R语言与其他语言的差异，给那些了解其他语言的开发人员提供参考。\n【相关图书推荐】\n978-7-111-40700-3 数据挖掘与R语言\n978-7-111-42021-7 R语言经典实例\n978-7-111-41731-6 机器学习：实用案例解析\n978-7-111-32572-7 时间序列分析及应用：R语言（原书第2版）','oprisk','Y',NULL,NULL,'admin',NULL);
INSERT INTO `OPRISK_BOOK_STORE` (`OPRISK_BOOK_STORE_ID`, `TITLE`, `AUTHOR`, `PUBLISH_DATE`, `SUB_TITLE`, `ORIGIN_TITLE`, `IMAGE`, `TRANSLATOR`, `PAGES`, `PRICE`, `PUBLISHER`, `ISBN_10`, `ISBN_13`, `AUTHOR_INTRO`, `SUMMARY`, `BOOK_OWNER`, `IS_IN_LIBRARY`, `IS_ACTIVE`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`) VALUES (11,'FRM2013notesBook4 ValuationandRisk Model','[]','2013',NULL,'','http://img3.douban.com/mpic/s27274720.jpg','[]',327,'','','1427744734','9781427744739','','','oprisk','Y',NULL,NULL,'admin',NULL);
INSERT INTO `OPRISK_BOOK_STORE` (`OPRISK_BOOK_STORE_ID`, `TITLE`, `AUTHOR`, `PUBLISH_DATE`, `SUB_TITLE`, `ORIGIN_TITLE`, `IMAGE`, `TRANSLATOR`, `PAGES`, `PRICE`, `PUBLISHER`, `ISBN_10`, `ISBN_13`, `AUTHOR_INTRO`, `SUMMARY`, `BOOK_OWNER`, `IS_IN_LIBRARY`, `IS_ACTIVE`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`) VALUES (12,'非说不可','[\"孟非\"]','2011-5-1',NULL,'','http://img4.douban.com/mpic/s23119187.jpg','[]',309,'35.00元','南京大学出版社','7305079367','9787305079368','孟非，不惑之年，还常有困惑；不意闻达，还是俗人一个；不喜争辩，有话还是非说不可！','本书是江苏广电总台著名主持人孟非的文集，内容生动丰富。在本书中，孟非从明星主持人身份还原到一位普通公民，以公民的视角对人生百态、社会全貌进行评论。通过解析新闻事件，进而进行评论，文辞生动、逻辑严密、内容丰富，具有可读性和收藏性。','oprisk','Y',NULL,NULL,'admin',NULL);
INSERT INTO `OPRISK_BOOK_STORE` (`OPRISK_BOOK_STORE_ID`, `TITLE`, `AUTHOR`, `PUBLISH_DATE`, `SUB_TITLE`, `ORIGIN_TITLE`, `IMAGE`, `TRANSLATOR`, `PAGES`, `PRICE`, `PUBLISHER`, `ISBN_10`, `ISBN_13`, `AUTHOR_INTRO`, `SUMMARY`, `BOOK_OWNER`, `IS_IN_LIBRARY`, `IS_ACTIVE`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`) VALUES (13,'英语语法新思维初级教程','[\"张满胜\"]','2008-1',NULL,'','http://img4.douban.com/mpic/s5921507.jpg','[]',298,'38.00元','群言出版社','7800808351','9787800808357','张满胜：英国剑桥大学英语硕士，北京新东方学校“新思维语法”培训创始人。拥有十多年的英语教学和研究经验，对英语语法有深入研究，目前正致力于考研英语的培训和研究工作。2003年以来一直在《新东方英语》杂志主持“新思维语法”专栏，深受广大读者的欢迎。','《英语语法新思维初级教程:走近语法》是一本“与众不同”的语法书：它不同于传统语法书只是机械地罗列教条式的“死规则”，它真的要告诉你规则背后的“活思维”；它不同于传统语法书追求“大而全”的规则排列，它真的要让你快速掌握“少而精”的思维规律；它不同于传统语法书那样本末倒置地给出较多生僻的“例外”，它真的让你高效掌握英语思维的本质；它不同于传统语法书采用枯燥的例句来讲解规则，读起来味同嚼蜡，它真的要让你在欣赏有趣例句、幽默故事以及精美短文的同时，领悟英语思维；它不同于传统语法书只给你孤立的、脱离语境的单一句子，它真的要让你知道例句背后的使用语境；它不同于传统语法书只教你语法知识，它真的要教你如何运用语法知识，从而把语法知识转化为你的语言技能，真正培养你创造性使用英语的能力。','oprisk','Y',NULL,NULL,'admin',NULL);
commit;

INSERT INTO `OPRISK_WX_CONFIG` (`OPRISK_WX_CONFIG_ID`, `TOKEN`, `CORP_ID`, `ENCODING_AES_KEY`, `IS_ACTIVE`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`) VALUES (1,'oprisk','wxc03949bd0004a4a3','QuivJW92IshM3IjUMzHqkbfyY7fJdOOvyfxTkFoawth','Y',NULL,'sf67958','2015-07-25 09:32:26');
INSERT INTO `OPRISK_WX_CONFIG` (`OPRISK_WX_CONFIG_ID`, `TOKEN`, `CORP_ID`, `ENCODING_AES_KEY`, `IS_ACTIVE`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`) VALUES (2,'oprisk','wxc03949bd0004a4a3','QuivJW92IshM3IjUMzHqkbfyY7fJdOOvyfxTkFoawth','N',NULL,'sf67958','2015-07-25 09:32:31');
commit;

INSERT INTO `OPRISK_WX_GROUP_SECRET` (`OPRISK_WX_GROUP_SECRET_ID`, `CORP_ID`, `CORP_SECRET`, `ACCESS_TOKEN_URL`, `WX_GROUP`, `DESCRIPTION`, `IS_ACTIVE`, `CREATED_BY`, `CREATED_DATE`) VALUES (1,'wxc03949bd0004a4a3','c4GNJ-kKHZrNRilDmZkPmS0itfdO6IPHhcZ_1YoAxrmc_24zw09VU-84sAEso9Y7','https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=:corpid&corpsecret=:corpsecret','oprisk',NULL,'Y','sf67958','2015-07-25 09:44:31');
commit;